/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef profile_CONSTANTS_H
#define profile_CONSTANTS_H

#include "profile_types.h"

namespace profile {

class profileConstants {
 public:
  profileConstants();

};

extern const profileConstants g_profile_constants;

} // namespace

#endif
