// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ProfileService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::profile;

class ProfileServiceHandler : virtual public ProfileServiceIf {
 public:
  ProfileServiceHandler() {
    // Your initialization goes here
  }

  void put(const int32_t id, const UserProfile& profile) {
    // Your implementation goes here
    printf("put\n");
  }

  void get(UserProfile& _return, const int32_t id) {
    // Your implementation goes here
    printf("get\n");
  }

  void remove(const int32_t id) {
    // Your implementation goes here
    printf("remove\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ProfileServiceHandler> handler(new ProfileServiceHandler());
  shared_ptr<TProcessor> processor(new ProfileServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

